<?php

$banco = array(
'156'=>'100% BANCO, BANCO COMERCIAL, C.A.',
'172'=>'BANCAMIGA BANCO MICROFINANCIERO, C.A.',
'171'=>'BANCO ACTIVO, C.A. BANCO COMERCIAL',
'166'=>'BANCO AGRICOLA DE VENEZUELA, C.A. BANCO UNIVERSAL',
'175'=>'BANCO BICENTENARIO BANCO UNIVERSAL, C.A.',
'128'=>'BANCO CARONI, C.A. BANCO UNIVERSAL',
'001'=>'BANCO CENTRAL DE VENEZUELA',
'141'=>'BANCO CONFEDERADO, S.A., BANCO COMERCIAL REGIONAL',
'177'=>'BANCO DE LA FUERZA ARMADA NACIONAL BOLIVARIANA,BANCO UNIVERSAL, C.A.',
'146'=>'BANCO DE LA GENTE EMPRENDEDORA BANGENTE, C.A.',
'102'=>'BANCO DE VENEZUELA S.A.C.A. BANCO UNIVERSAL',
'114'=>'BANCO DEL CARIBE, C.A. BANCO UNIVERSAL',
'149'=>'BANCO DEL PUEBLO SOBERANO, C.A. BANCO DE DESARROLLO',
'163'=>'BANCO DEL TESORO, C.A. BANCO UNIVERSAL',
'176'=>'BANCO ESPIRITO SANTO, S.A.',
'115'=>'BANCO EXTERIOR, C.A. BANCO UNIVERSAL',
'008'=>'BANCO GUAYANA, C.A.',
'003'=>'BANCO INDUSTRIAL DE VENEZUELA, C.A.',
'173'=>'BANCO INTERNACIONAL DE DESARROLLO, C.A.',
'105'=>'BANCO MERCANTIL, C.A. S.A.C.A. BANCO UNIVERSAL',
'191'=>'BANCO NACIONAL CRÉDITO, C.A. BANCO UNIVERSAL',
'116'=>'BANCO OCCIDENTAL DE DESCUENTO BANCO UNIVERSAL',
'138'=>'BANCO PLAZA, C.A.',
'108'=>'BANCO PROVINCIAL, S.A. BANCO UNIVERSAL',
'137'=>'BANCO SOFITASA BANCO UNIVERSAL, C.A.',
'168'=>'BANCRECER S.A. BANCO DE DESARROLLO',
'134'=>'BANESCO BANCO UNIVERSAL S.A.C.A.',
'007'=>'BANFOANDES, BANCO UNIVERSAL, C.A.',
'147'=>'BANORTE',
'174'=>'BANPLUS BANCO COMERCIAL, C.A. ',
'151'=>'BFC BANCO FONDO COMUN C.A. BANCO UNIVERSAL',
'150'=>'BOLÍVAR BANCO, C.A.',
'158'=>'C.A., CENTRAL BANCO UNIVERSAL',
'190'=>'CITIBANK N.A.',
'157'=>'DEL SUR BANCO UNIVERSAL, C.A.',
'601'=>'INSTITUTO MUNICIPAL DE CRÉDITO POPULAR',
'169'=>'MI BANCO, BANCO DE DESARROLLO, C.A. ',
'104'=>'VENEZOLANO DE CRÉDITO, S.A. BANCO UNIVERSAL'
);

return array(
    'listabancos' => $banco
);